config/routes.rb
Workoutapp::Application.routes.draw do
  devise_for :users

  devise_scope :user do
      get "login", :to => "devise/sessions#new", :as => :login
      get "logout", :to => "devise/sessions#destroy", :as => :logout
      get "register", :to => "devise/registrations#new", :as => :register
  end

  authenticated :user do
    root :to => "home#index"
  end

  match '/profile', :to => 'user#profile', :as => :profile
  match '/profile/edit', :to => 'user#edit_profile', :as => :edit_profile
  match '/profile/update', :to => 'user#update_profile', :as => :update_profile

  resources :goals

  resources :exercises

  root :to => "public#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Dashboard</h1>
<ul class="dashboard-options">
  <%= link_to profile_path, do %>
  <li class="dashboard-option">
    <figure class="dashboard-icon profile"></figure>
    <figcaption>
    Profile
    </figcaption>
  </li>
  <% end %>
  <%= link_to goals_path, do %>
  <li class="dashboard-option">
    <figure class="dashboard-icon goals"></figure>
    <figcaption>
    Goals
    </figcaption>
  </li>
  <% end %>
  <br/>
  <%= link_to "#", do %>
  <li class="dashboard-option">
    <figure class="dashboard-icon journal"></figure>
    <figcaption>
    Journal
    </figcaption>
  </li>
  <% end %>
  <%= link_to "#", do %>
  <li class="dashboard-option">
    <figure class="dashboard-icon progress"></figure>
    <figcaption>
     Progress
    </figcaption>
  </li>
  <% end %>
</ul>