config/routes.rb
Workoutapp::Application.routes.draw do
  devise_for :users

  devise_scope :user do
      get "login", :to => "devise/sessions#new", :as => :login
      get "logout", :to => "devise/sessions#destroy", :as => :logout
      get "register", :to => "devise/registrations#new", :as => :register
  end

  authenticated :user do
    root :to => "home#index"
  end

  match '/profile', :to => 'user#profile', :as => :profile
  match '/profile/edit', :to => 'user#edit_profile', :as => :edit_profile
  match '/profile/update', :to => 'user#update_profile', :as => :update_profile

  resources :goals

  resources :exercises

  root :to => "public#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :login, :age, :gender, :weight, :height, :body_fat_pct, :activity_level
  attr_accessor :login

  has_many :goals



  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def has_complete_profile?
    return self.weight.present? && self.age.present? && self.gender.present? && self.height.present? && self.body_fat_pct.present? && self.activity_level.present?
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def edit_profile
    @activity_levels = [
      ['Little or No Exercise', 1],
      ['Light Exercise/Sports 1-3 Days a Week', 2],
      ['Moderate Exercise/Sports 3-5 Days a Week', 3],
      ['Hard Exercise/Sports 6-7 Days a Week', 4],
      ['Very Hard Exercise/Sports & Physical Job or 2x Training', 5]
    ]
    @heights = Metrics.get_heights
    @body_metrics = Metrics.get_body_metrics(current_user)

  end

  def update_profile
    current_user.update_attributes(params[:user])
    redirect_to profile_path(current_user.id) and return
  end

  def profile
    @user = User.find_by_id(params[:user_id]) || current_user

    if @user.nil?
      redirect_to profile_path(current_user.id) and return
    end

    @activity_level = Metrics.get_activity_levels(@user.activity_level)
    @body_metrics = Metrics.get_body_metrics(@user)
    @height = Metrics.get_ft_and_in(@user.height)

  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit_profile.html.erb
<h1>Edit Your Profile</h1>

<div class="profile-wrapper">
  <div class="left">
    <figure class="profile-pic">
      <%= image_tag "http://www.wallpaperswala.com/wp-content/gallery/ronnie-coleman/ronnie-coleman-showing-body.jpg", :width => "100%", :height => "100%" %>
    </figure>
    <h3>@<%= current_user.username %></h3>
    <h3>Joined on <%= current_user.created_at.strftime("%b %d, %Y") %></h3>
  </div>

  <div class="right">
    <%= form_for(current_user, :url => update_profile_path(current_user), :html => { :id => 'edit-profile-form' } ) do |f| %>

    <div class="fieldset">
      <%= f.label :age, :class => "inline sm" %>
      <%= f.number_field :age, :class => "inline sm", :id => "user-age" %>
    </div>

    <div class="fieldset">
      <%= f.label :gender, :class => "inline sm" %>
      <%= f.radio_button(:gender, "Male", :id => "user-gender-male") %>Male
      <%= f.radio_button(:gender, "Female", :id => "user-gender-female") %>Female
    </div>

    <div class="fieldset">
      <%= f.label :weight, :class => "inline sm" %>
      <%= f.text_field :weight, :class => "inline sm", :id => "user-weight" %> lbs
    </div>

    <div class="fieldset">
      <%= f.label :height, :class => "inline sm" %>
      <%= f.select(:height, options_for_select(@heights[:us], :selected => "#{current_user.height.to_i}"), {}, :id => "user-height") %>

    </div>

    <div class="fieldset">
      <%= f.label :body_fat, "Body Fat", :class => "inline sm",%>
      <%= f.text_field :body_fat_pct, :class => "inline sm", :id => "user-body-fat-pct" %>%
    </div>

    <div class="fieldset">
      <%= f.label :activity_level, "Activity Level", :class => "inline sm" %>
      <%= f.select(:activity_level, options_for_select(@activity_levels, :selected => current_user.activity_level), {}, :class => "inline lg", :id => "user-activity-level" ) %>
    </div>

    <div class="fieldset">
      <label class="inline sm">LBM</label>
      <span class="inline lbm"><%= @body_metrics[:lbm] if @body_metrics %></span> lbs
    </div>

    <div class="fieldset">
      <label class="inline sm">BMR</label>
      <span class="inline bmr"><%= @body_metrics[:bmr] if @body_metrics %></span>
    </div>

    <div class="fieldset">
      <label class="inline sm">Calories/Day</label>
      <span class="inline hbf"><%= @body_metrics[:hbf] if @body_metrics %></span>
    </div>


    <div class="fieldset submit">
      <%= f.label :" ", :class => "inline sm" %>
      <%= f.submit "Update Profile", :class => "md round btn gold" %>
      or <%= link_to "Cancel", profile_path(current_user.id) %>
    </div>
  <% end %>

  </div>
</div>

<script type="text/javascript">
    var options       = {
                          'containers': {
                            'form': '#edit-profile-form',
                            'bmr': '.bmr',
                            'hbf': '.hbf',
                            'lbm': '.lbm',
                            'age-input': '#user-age',
                            'gender-male-input': '#user-gender-male',
                            'gender-female-input': '#user-gender-female',
                            'weight-input': '#user-weight',
                            'height-input': '#user-height',
                            'body-fat-pct-input': '#user-body-fat-pct',
                            'activity-level-input': '#user-activity-level'
                          }
                        },
        profileEditor = new ProfileEditor(options);

  profileEditor.initControls();
</script>

app/views/user/profile.html.erb
<% if current_user.id == @user.id %>
  <h1>Your Profile</h1>
<% else %>
  <h1>@<%= @user.username %>'s Profile</h1>
<% end %>

<div class="profile-wrapper">
  <div class="left">
    <figure class="profile-pic">
      <%= image_tag "http://www.wallpaperswala.com/wp-content/gallery/ronnie-coleman/ronnie-coleman-showing-body.jpg", :width => "100%", :height => "100%" %>
    </figure>
    <h3>@<%= @user.username %></h3>
    <h3>Joined on <%= @user.created_at.strftime("%b %d, %Y") %></h3>
    <% if current_user.id == @user.id %>
    <p>
      <%= link_to "Edit", edit_profile_path %>
    </p>
    <% end %>
  </div>

  <div class="right">

    <div class="fieldset">
      <%= label_tag :age, 'Age', :class => "inline sm" %>
      <span class="inline"><%= @user.age %></span>
    </div>

    <div class="fieldset">
      <%= label_tag :gender, 'Gender', :class => "inline sm" %>
      <span class="inline"><%= @user.gender %></span>
    </div>

    <div class="fieldset">
      <%= label_tag :weight, 'Weight', :class => "inline sm" %>
      <span class="inline"><%= @user.weight %> lbs</span>
    </div>

    <div class="fieldset">
      <%= label_tag :height, 'Height', :class => "inline sm" %>
      <span class="inline"><%= @height %></span>
    </div>

    <div class="fieldset">
      <%= label_tag :"Body Fat", 'Body Fat', :class => "inline sm" %>
      <span class="inline"><%= @user.body_fat_pct %>%</span>
    </div>

    <div class="fieldset">
      <%= label_tag :activity_level, 'Activity Level', :class => "inline sm" %>
      <span class="inline"><%= @activity_level %></span>
    </div>

    <div class="fieldset">
      <label class="inline sm">LBM</label>
      <span class="inline lbm"><%= @body_metrics[:lbm] if @body_metrics %> lbs</span>
    </div>

    <div class="fieldset">
      <label class="inline sm">BMR</label>
      <span class="inline bmr"><%= @body_metrics[:bmr] if @body_metrics %></span>
    </div>

    <div class="fieldset">
      <label class="inline sm">Calories/Day</label>
      <span class="inline hbf"><%= @body_metrics[:hbf] if @body_metrics %></span>
    </div>

  </div>
</div>