config/routes.rb
Workoutapp::Application.routes.draw do
  devise_for :users

  devise_scope :user do
      get "login", :to => "devise/sessions#new", :as => :login
      get "logout", :to => "devise/sessions#destroy", :as => :logout
      get "register", :to => "devise/registrations#new", :as => :register
  end

  authenticated :user do
    root :to => "home#index"
  end

  match '/profile', :to => 'user#profile', :as => :profile
  match '/profile/edit', :to => 'user#edit_profile', :as => :edit_profile
  match '/profile/update', :to => 'user#update_profile', :as => :update_profile

  resources :goals

  resources :exercises

  root :to => "public#index"

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :description, :due_date, :final_value, :start_value, :goal_type, :user_id, :name

  belongs_to :user

  GOAL_TYPES = {
    :lose_fat => "LF",
    :gain_muscle => "GM"
  }

  FRIENDLY_GOAL_TYPES = {
    "LF" => "Lose Fat",
    "GM" => "Gain Muscle"
  }

  def self.get_goal_types
    [
      ["", ""],
      ["Lose Fat", self::GOAL_TYPES[:lose_fat]],
      ["Gain Muscle", self::GOAL_TYPES[:gain_muscle]]
    ]
  end

  def self.get_friendly_goal_types(goal_type)
    return self::FRIENDLY_GOAL_TYPES[goal_type]
  end

  def self.validate_goal(goal_params, user)
    fields = {
      :name => "#goal-name",
      :goal_type => "#goal-type",
      :due_date => "#goal-due-date",
      :final_value => "#goal-final-value",
      :description => "#goal-description"
    }

    goal_hash = {
      "errors" => [],
      "params" => goal_params
    }

    if user.nil?
      goal_hash["errors"] << "Invalid User"
    end

    # check goal name
    if goal_params[:name].blank?
      goal_hash["errors"] << {
        "field" => fields[:name],
        "message" => "Please enter a goal name"
      }
    end

    # check goal weight
    if goal_params[:final_value].blank?
      goal_hash["errors"] << {
        "field" => fields[:final_value],
        "message" => "Please enter a goal weight"
      }
    end

    # check goal type
    if !self::GOAL_TYPES.values().include?(goal_params[:goal_type])
      goal_hash["errors"] << {
        "field" => fields[:goal_type],
        "message" => "Please choose a valid goal type"
      }
    end

    # check date
    begin
      due_date = DateTime.strptime(goal_params[:due_date], "%m/%d/%Y")
      if due_date < DateTime.now
        goal_hash["errors"] << {
          "field" => fields[:due_date],
          "message" => "Please set a date in the future"
        }
      else
        goal_hash["params"][:due_date] = due_date
      end
    rescue
      goal_hash["errors"] << {
        "field" => fields[:due_date],
        "message" => "Please select a valid date"
      }
    end

    # check goal type against values
    if goal_params[:goal_type] == self::GOAL_TYPES[:lose_fat]
      if goal_params[:final_value].to_f > user.weight
        goal_hash["errors"] << {
          "field" => fields[:final_value],
          "message" => "To lose fat, you must enter a value less than your current weight"
        }
      end
    elsif goal_params[:goal_type] == self::GOAL_TYPES[:gain_muscle]
      if goal_params[:final_value].to_f < user.weight
        goal_hash["errors"] << {
          "field" => fields[:final_value],
          "message" => "To gain muscle, you must enter a value greater than your current weight"
        }
      end
    end

    return goal_hash
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @goals = current_user.goals
  end

  def show
    @goal = Goal.find_by_id(params[:id])
    if request.xhr?
      render :nothing => true and return if @goal.user.id != current_user.id
      @ajax = true
    else
      redirect_to goals_path and return if @goal.nil?
    end
    @goal_user = @goal.user

    @friendly_goal_type = Goal.get_friendly_goal_types(@goal.goal_type)

    @body_metrics = Metrics.get_body_metrics(@goal_user)

    if @goal.goal_type == Goal::GOAL_TYPES[:gain_muscle]
      # 250 - 500 caloric surplus per day
      @calories_per_day = (@body_metrics[:hbf].to_f * 2 + 750)/2
    elsif @goal.goal_type == Goal::GOAL_TYPES[:lose_fat]
      @calories_per_day_hash = Metrics.get_daily_target_calories(@goal_user, @goal)
    end
  end

  def new
    if current_user.has_complete_profile?
      @new_goal = Goal.new
      @goal_types = Goal.get_goal_types
    end
  end

  def create
    @goal_hash = Goal.validate_goal(params[:goal], current_user)
    if @goal_hash["errors"].present?
      @success = false
      logger.debug(@goal_hash)
    else
      params[:goal][:start_value] = current_user.weight
      params[:goal][:due_date] = @goal_hash["params"][:due_date]
      @goal = current_user.goals.new(params[:goal])
      if @goal.save
        @success = true
      else
        @success = false
      end
    end
  end

  def destroy
    @goal = Goal.find_by_id(params[:id])
    redirect_to goals_path and return if @goal.nil? || @goal.user.id != current_user.id
    @goal.destroy
    redirect_to goals_path and return
  end

  def update
    @goal = Goal.find_by_id(params[:id])
    render :nothing => true and return if @goal.nil?
    render :nothing => true and return if @goal.user.id != current_user.id

    goal_change = params[:change]
    if goal_change == "ne-ratio"
      @nutrition_pct = params[:nutrition]
      @exercise_pct = params[:exercise]
      @goal.nutrition = @nutrition_pct
      @goal.exercise = @exercise_pct
      if @goal.save
        @success = true
        @calories_per_day_hash = Metrics.get_daily_target_calories(@goal.user, @goal)
      end
    end
    render 'update' and return
  end
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/views/goals/_show.html.erb
  <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
  <div class="fieldset">
    <div class="left">
      <label class="inline sm">Goal</span>
    </div>
    <div class="right">
      <span class="inline lg"><%= @friendly_goal_type %></span>
    </div>
  </div>

  <div class="fieldset">
    <div class="left">
      <label class="inline sm">Reach Goal By</span>
    </div>
    <div class="right">
      <span class="inline sm"><%= @goal.due_date.strftime("%b %e, %Y") %> (<%= distance_of_time_in_words(DateTime.now, @goal.due_date.to_datetime) %> left)</span>
    </div>
  </div>

  <div class="fieldset">
    <div class="left">
      <label class="inline sm">Starting Weight</span>
    </div>
    <div class="right">
      <span class="inline sm"><%= @goal.start_value %> lbs</span>
    </div>
  </div>

  <div class="fieldset">
    <div class="left">
      <label class="inline sm">Final Weight</span>
    </div>
    <div class="right">
      <span class="inline sm"><%= @goal.final_value %> lbs</span>
    </div>
  </div>

  <div class="fieldset">
    <div class="left">
      <label class="inline sm">Description</span>
    </div>
    <div class="right">
      <span class="inline sm"><%= @goal.description %></span>
    </div>
  </div>

  <div class="fieldset">
    <div class="left">
      <label class="inline md">Caloric Intake (Nutrition)</span>
    </div>
    <div class="right">
      <span class="inline sm"><%= @calories_per_day_hash[:calories_to_gain_via_nutrition] %></span>
    </div>
  </div>

  <div class="fieldset">
    <div class="left">
      <label class="inline md">Caloric Exhaustion (Exercise)</span>
    </div>
    <div class="right">
      <span class="inline sm">- <%= @calories_per_day_hash[:calories_to_burn_per_day_via_exercise] %></span>
    </div>
  </div>

  <div class="fieldset total">
    <div class="left">
      <label class="inline md">Total Calories/Day</span>
    </div>
    <div class="right">
      <span class="inline sm"><%= @calories_per_day_hash[:target_calories_per_day] %></span>
    </div>
  </div>

  <% if @ajax %>
  <div class="fieldset">
    <div class="left">
      <label class="inline sm"></span>
    </div>
    <div class="right">
      <span class="inline sm"><%= link_to "More →", goal_path(@goal.id) %></span>
    </div>
  </div>
  <% end %>

app/views/goals/create.js.erb
$('.error').addClass('inactive');

<% if @success %>
    goal.handleFormSuccess('<%= goal_path(@goal.id) %>');
<% else %>
  <% @goal_hash["errors"].each do |error| %>
    $('<%= error["field"] %>').next('.error').text('<%= escape_javascript(error["message"]) %>').removeClass('inactive');
  <% end %>
<% end %>

goal.formSubmitted = true;

app/views/goals/index.html.erb
<h1>Your Goals</h1>

<div class="goals-wrapper eight columns">
  <% if @goals.present? %>
    <ul class="goals-list">
    <% @goals.each do |goal| %>
      <li class="goal-item">
        <%= link_to "#{goal.name}", goal_path(goal.id), :class => "goal-preview", :"data-goal-id" => goal.id %>
        <%= link_to image_tag("edit.png"), edit_goal_path(goal.id), :class => "goal-inline-edit" %>
        <%= link_to image_tag("delete.png"), goal_path(goal.id), :method => :delete, :class => "goal-delete" %>
      </li>
    <% end %>
    </ul>
  <% else %>
    <p>You do not have any goals.</p>
  <% end %>
</div>

<div class="goal-preview-container eight columns">
  <div class="goal-preview-wrapper inactive">
  </div>
</div>
<div class="eight columns offset-by-four create-goal-wrapper">
  <%= link_to "+ Create a new goal!", new_goal_path(), :class => "lg gold btn" %>
</div>

<script type="text/javascript">

  var options       = {
                        'containers': {
                          'previewContainer': '.goal-preview-wrapper',
                          'goalsListContainer': '.goals-list'
                        },
                        'previewGoalBaseUrl': '<%= goals_path %>'
                      },
  goalPreview = new GoalPreview(options);

  goalPreview.initControls();

</script>

app/views/goals/new.html.erb
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>

<div class="goals-wrapper nine columns">
  <h1>Create a Goal</h1>
  <% if @new_goal %>
    <%= form_for(@new_goal, :url => goals_path(current_user), :html => { :id => 'new-goal-form' }, :remote => true ) do |f| %>

    <div class="fieldset">
      <div class="left">
      <%= f.label :name, "Goal Name", :class => "inline sm" %>
      </div>
      <div class="right">
        <%= f.text_field :name, :class => "inline md", :id => "goal-name" %>
        <div class="error inactive"></div>
      </div>
    </div>

    <div class="fieldset">
      <div class="left">
      <%= f.label :goal_type, "Goal Type", :class => "inline sm" %>
      </div>
      <div class="right">
        <%= f.select(:goal_type, options_for_select(@goal_types), {}, :class => "inline md", :id => "goal-type" ) %>
        <div class="error inactive"></div>
      </div>
    </div>

    <!--
    <div class="fieldset">
      <div class="left">
        <%= label_tag :importance, "Importance", :class => "inline sm" %>
      </div>
      <div class="right">
        <%= select_tag :importance, options_for_select([["Steady Fat Loss", "steady"], ["Drastic Fat Loss", "drastic"]]), :include_blank => true, :id => "goal-importance", :class => "inline md" %>
        <div class="error inactive"></div>
      </div>
    </div>
    -->

    <div class="fieldset">
      <div class="left">
        <%= f.label :due_date, "Reach Goal By", :class => "inline sm" %>
      </div>
      <div class="right">
        <%= f.text_field :due_date, :id => "goal-due-date", :class => "inline md datepicker" %>
        <div class="error inactive"></div>
      </div>
    </div>

    <div class="fieldset">
      <div class="left">
        <%= label_tag :start_value , "Current Weight", :class => "inline sm" %>
      </div>
      <div class="right">
        <%= number_field_tag :start_value, current_user.weight, :id => "goal-start-value", :disabled => "disabled", :class => "inline sm" %> lbs
      </div>
    </div>

    <div class="fieldset">
      <div class="left">
        <%= f.label :final_value , "Goal Weight", :class => "inline sm" %>
      </div>
      <div class="right">
        <%= f.number_field :final_value, :id => "goal-final-value", :class => "inline sm" %> lbs
        <div class="error inactive"></div>
      </div>
    </div>

    <div class="fieldset">
      <div class="left">
        <%= f.label :description, "Description", :class => "inline sm" %>
      </div>
      <div class="right">
        <%= f.text_area :description, :id => "goal-description", :class => "inline sm", :placeholder => "(Optional)", :size => "40x4" %>
      </div>
    </div>

    <div class="fieldset inactive">
      <div class="left">
        <%= label_tag :delta, "Desired Goal", :class => "inline sm" %>
      </div>
      <div class="right">
        <span id="goal-delta"></span> lbs over <span id="delta-time"></span> days
        <span id="goal-rate"></span>
      </div>
    </div>

    <div class="fieldset submit">
      <div class="left">
        <%= f.label :" ", :class => "inline sm" %>
      </div>
      <div class="right">
        <%= f.submit "Begin Your Goal", :class => "md round btn gold", :id => "goal-submit", :disabled => "disabled" %>
        or <%= link_to "Cancel", goals_path %>
      </div>
    </div>
    <% end %>
  <% else %>
    <p>To create a goal, you must first complete your <%= link_to "profile", :edit_profile %>
  <% end %>
</div>

<div class="notes-wrapper seven columns">
  <h2>Protips</h2>
  <ul class="notes-list">
    <li>You should only achieve goals <strong>one at a time</strong></li>
    <li><strong>Be held accountable</strong> for achieving/failing your goal</li>
    <li>Make <strong>SMART</strong> goals</li>
    <ul class="smart-list">
      <li><strong>S</strong>pecific - Goal should be clear and unambiguous</li>
      <li><strong>M</strong>easurable - Be able to measure your progress</li>
      <li><strong>A</strong>ttainable - Goal should be realisitic</li>
      <li><strong>R</strong>elevant - Choose a goal that matters</li>
      <li><strong>T</strong>ime-bound - Give your goal a time frame</li>
    </ul>
  </ul>
</div>

<script type="text/javascript">

  var options       = {
                        'containers': {
                          'form': '#new-goal-form',
                          'goal-name-input': '#goal-name',
                          'goal-type-input': '#goal-type',
                          'due-date-input': '#goal-due-date',
                          'start-value-input': '#goal-start-value',
                          'final-value-input': '#goal-final-value',
                          'delta-input': '#goal-delta',
                          'delta-time': '#delta-time',
                          'goal-description-input': '#goal-description',
                          'goal-submit': '#goal-submit',
                          'goal-rate': '#goal-rate'
                        },
                        'submitUrl': '<%= goals_path() %>'
                      },
  goal = new Goal(options);

  goal.initControls();

  $().ready(function() {
    var tomorrow = new Date( (new Date()).getTime() + 24 * 60 * 60 * 1000 );
    $('.datepicker').datepicker({
      minDate: tomorrow
    });
    $('#goal-final-value').regexMask(/^\d+(,\d+)?$/);
  });

</script>

app/views/goals/show.html.erb
<div class="eight columns goals-wrapper">
  <h1>Your Goal: <%= @goal.name %></h1>
  <%= render :partial => "show" %>
</div>


<div class="eight columns goals-details-wrapper">

  <hr class="md solid"/>

  <p class="summary">Based on your goal of <em><%= @friendly_goal_type %></em>
  by <em><%= @goal.due_date.strftime("%b %e, %Y") %> (<%= @calories_per_day_hash[:days_until_goal] %> days left)</em>
  and a <em>nutrition/exercise</em> ratio of <strong><span class="nutrition-ratio"><%= @goal.nutrition %></span>/<span class="exercise-ratio"><%= @goal.exercise %></span></strong>,
  we have determined you need to have a <em>caloric deficit</em> of <strong><%= @calories_per_day_hash[:daily_caloric_deficit] %>/day</strong>.
  <em>Nutrition</em>: <strong class="nutrition-calories"><%= @calories_per_day_hash[:daily_nutrition_caloric_deficit] %></strong> & 
  <em>Exercise</em>: <strong class="exercise-calories"><%= @calories_per_day_hash[:daily_exercise_caloric_deficit] %></strong></p>

  <% if current_user.id == @goal.user_id && @goal.goal_type == "LF" %>
  <h3>Nutrition/Exercise Ratio</h3>
  <div class="slider-wrapper">
    <div class="nutrition-wrapper slider-label">
      <p><strong>Nutrition</strong></p>
      <span class="ratio"><%= @goal.nutrition %>%</span>
    </div>
    <div class="inline sm slider"></div>
    <div class="exercise-wrapper slider-label">
      <p><strong>Exercise</strong></p>
      <span class="ratio"><%= @goal.exercise %>%</span>
    </div>
  </div>
  <p class="slider-status"></p>
  <% else %>
  <% end %>


</div>

<div class="sixteen columns">

  <h2>Current Progress</h2>
  <div class="fieldset">
    <div class="left">
      <label class="inline md">Current Weight</span>
    </div>
    <div class="right">
      <span class="inline sm"><%= @goal.user.weight %> lbs</span>
    </div>
  </div>
  <div class="fieldset">
    <div class="left">
      <label class="inline md">Weight Left til Goal</span>
    </div>
    <div class="right">
      <span class="inline sm"><%= @goal.user.weight - @goal.final_value %> lbs</span>
    </div>
  </div>
  <div class="fieldset">
    <div class="left">
      <label class="inline md">Status</span>
    </div>
    <div class="right">
      <span class="inline sm">On Track!</span>
    </div>
  </div>

</div>

  <script type="text/javascript">
    $().ready(function() {
      var slideSaveTimer;
      $('.slider').slider({
        range: 'max',
        min: 0,
        max: 100,
        value:  <%= @goal.nutrition %>,
        slide: function( event, ui ) {
          clearTimeout(slideSaveTimer);
          var nutritionPct  = ui.value,
              exercisePct   = 100 - nutritionPct;
          $('.nutrition-wrapper .ratio').text(nutritionPct + '%');
          $('.exercise-wrapper .ratio').text(exercisePct + '%');

          slideSaveTimer = setTimeout(function() {
            $.ajax({
              url: '<%= goal_path(@goal) %>',
              data: {
                'change': 'ne-ratio',
                'nutrition': nutritionPct,
                'exercise': exercisePct
              },
              type: 'PUT'
            });
          }, 1000);
        }
      });
    });
  </script>

app/views/goals/show.js.erb
goalPreview.$previewContainer.html('<%= escape_javascript(render :partial => "show") %>').removeClass('inactive');

app/views/goals/update.js.erb
<% if @success %>
  $('.summary .nutrition-ratio').text('<%= @nutrition_pct %>');
  $('.summary .exercise-ratio').text('<%= @exercise_pct %>');

  $('.summary .nutrition-calories').text('<%= @calories_per_day_hash[:daily_nutrition_caloric_deficit] %>');
  $('.summary .exercise-calories').text('<%= @calories_per_day_hash[:daily_exercise_caloric_deficit] %>');

  $('.slider-status').text('Saved!').show().delay(5000).fadeOut();
<% else %>
  $('.slider-status').text('Sorry, we could not update this ratio. Please slide again.');
<% end %>