config/routes.rb
Workoutapp::Application.routes.draw do
  devise_for :users

  devise_scope :user do
      get "login", :to => "devise/sessions#new", :as => :login
      get "logout", :to => "devise/sessions#destroy", :as => :logout
      get "register", :to => "devise/registrations#new", :as => :register
  end

  authenticated :user do
    root :to => "home#index"
  end

  match '/profile', :to => 'user#profile', :as => :profile
  match '/profile/edit', :to => 'user#edit_profile', :as => :edit_profile
  match '/profile/update', :to => 'user#update_profile', :as => :update_profile

  resources :goals

  resources :exercises

  root :to => "public#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workoutapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<header>
  <section class="container">
    <div class="sixteen-columns">
      <%= link_to "LOGO GOES HERE", :root, :id => "logo" %>
      <nav>
      <% if user_signed_in? %>
        <ul class="nav-options">
          <li class="option">
            <figure class="nav-icon home"></figure>
            <figcaption><%= link_to "Home", root_path %></figcaption>
          </li>
          <li class="option">
            <figure class="nav-icon exercises"></figure>
            <figcaption><%= link_to "Exercises", exercises_path %></figcaption>
          </li>
          <li class="option">
            <figure class="nav-icon logout"></figure>
            <figcaption><%= link_to "Log Out", logout_path, :class => "last" %></figcaption>
          </li>
        </ul>
      <% else %>
        <%= link_to "Sign Up", :register %> to track your stats!
        <%= link_to "Log In", :login %> to track your stats!
      <% end %>
    </nav>
    </div>
  </section>
</header>

<section class="container main">
    <div class="sixteen-columns">
    <%= yield %>
    </div>
</section>

<footer>
  <section class="container">
    <div class="sixteen-columns">
      &copy; Copyright 2013, Workoutapp, Inc. All Rights Reserved 
      &middot; Privacy
      &middot; Terms
      &middot; Support
    </div>
  </section>
</footer>

</body>

</html>